server:
  servlet:
    #  定义项目的访问访问路径
    context-path: /onlineshopping-consumer-server
    # 定义端口号
  port: 7011
spring:
  application:
    # 定义应用名称，即服务名称
    name: onlineshopping-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localtest?serverTimezone=GMT&useSSL=false&autoReconnect=true
    #    url: jdbc:mysql://localhost:3306/localtest?serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8051/onlineshopping-eureka-server/eureka,http://peer2:8052/onlineshopping-eureka-server/eureka,http://peer3:8053/onlineshopping-eureka-server/eureka